### ISSUE TITLE
Remove `@dojo/core/load` for loading CLDR data and translations

### ISSUE THREAD

**Issue by mwistrand** [dojo/i18n#106]
**Enhancement**

Given TypeScript's support for `import()`, we should consider updating `i18n()` to delegate translation loading to the bundles and CLDR data loading to applications. For example, a default message bundle would become something like the following:

```ts
// src/nls/main.ts
import fr from './fr/main';

export default {
    locales: {
        fr: () => fr,
        es: () => import('./es/main')
    },
    messages: {
        // ...
    }
};
```

Locale-specific translations will be loaded by functions on a `locales` object rather than by `@dojo/i18n` itself, and can be loaded either directly or lazily loaded with `import()` or `require()`.

CLDR data will be injected into the i18n system as well rather than loaded from URLs. For applications using `@dojo/cli-build-webpack`, URLs can be added to the `.dojorc` and the data will be injected at build time.

**Comment by dasa** [comment]
Is this going to be in Beta 5?

**Comment by mwistrand** [comment]
@dasa Yes; we have open PRs across the Dojo 2 repos that are ready to land, it's just a question of timing with upcoming changes to the build process.
