### ISSUE TITLE
Adopt Globalize.js?

### ISSUE THREAD

**Issue by mwistrand** [dojo/i18n#12]
Ultimately `dojo-i18n` should provide complete globalization support, including everything from message loading and formatting to locale-specific date and number formatting. Ideally we could offload some of this functionality to an existing high-quality library like [Globalize.js](https://github.com/jquery/globalize), which I believe was part of the plan to begin with.

However, as nice as Globalize it, as far as I can tell it is a single, all-or-nothing module. So if a developer only needs message formatting support, s/he still ends up with all of the CLDR data and date/number formatting (although I still need confirm that the CLDR data are unconditionally loaded).

I now wonder if `dojo-i18n` should expose a `formatMessage` method that takes a message key and configuration object to parse [ICU MessageFormat messages](http://userguide.icu-project.org/formatparse/messages) into their final result. Beyond that, we can either provide a separate module that wraps something like Globalize.js in a Dojo-specific format, or suggest that it be used independently for the additional functionality.

**Comment by dylans** [comment]
I thought Globalize was modular ( https://github.com/jquery/globalize#pick-the-modules-you-need ), and I thought it provided a way to get CLDR data and optimize the pieces you need.

That said, if they're off the mark or not making this easy for us, I'm happy to give them feedback on what they could do to make it easier to support their efforts. I just need more detail so I can chat with them.

**Comment by mwistrand** [comment]
You're right, @dylans. I was looking at examples that seemed to pull in the entire package.
