### ISSUE TITLE
Write I18n#loadBundle()

### ISSUE THREAD

**Issue by morrinene** [dojo/i18n#2]
I18n#loadBundle() will need to function similarly to Dojo 1's i18n plugin: Grab the root bundle and then any available bundles up to and including the user's locale. 

These will all be inserted into Globalize with the locale (`this.globalize.loadMessages({ en: bundle })`) and Globalize will figure out the correct message to use.

**Comment by kitsonk** [comment]
Re-starting i18n, therefore closing this.
