### ISSUE TITLE
Reducing the impact of CLDR data

### ISSUE THREAD

**Issue by mwistrand** [dojo/i18n#48]
Any application that utilizes `@dojo/i18n` needs to include CLDR data for any supported locales within its build. Globalize.js provides a compiler that can statically extract and precompile formatters, but because a Dojo 2 application can simultaneously support multiple locales and because the Globalize.js methods are passed their options through `@dojo/i18n` methods, this compiler cannot be used.

One way to reduce the need to include CLDR data in a build is to use the native `Intl` object where it is supported. `cldr/load/webpack` could then be updated to load the CLDR data only in environments where `Intl` is either not supported or only partially supported. Unfortunately, there may not be a way to accomplish this without removing Globalize.js from the `i18n` method. Since Globalize.js still requires CLDR data for ICU-formatted messages, the CLDR data would still be loaded regardless of `Intl` support.

**Comment by dylans** [comment]
How large is the CLDR data?

I think the Dojo 1 way was to sort of include a set of 20-30 locales by default which kept it from getting very large.

Perhaps we can raise this issue with the globalize team as well, to see if they have any better suggestions?

**Comment by msssk** [comment]
I added `dojo/i18n` to dgrid 2 and ended up with about 250MB, 14K files for `cldr-data`, `cldr-data-downloader`, `cldrjs`, and `globalize`.

**Comment by dylans** [comment]
> I added dojo/i18n to dgrid 2 and ended up with about 250MB, 14K files for cldr-data, cldr-data-downloader, cldrjs, and globalize.

Oh is that all? ;)

**Comment by mwistrand** [comment]
I can cut the core download size from 250MB to ~145MB by making the non-Gregorian calendar downloads optional, but all of the date/currency/number/unit data are still downloaded for about 350 locales. As far as I'm aware, GitHub does not provide a means of specifying which directories to include in zip archives. If that is truly the case, then we can 1) live with the 145MB download, 2) write a utility that downloads only the (uncompressed) directories for a specified list of locales from the various CLDR repositories, or 3) go the Dojo 1 route and include a set list of locales directly in the repo. If we went the third route, we would still want to provide a way to use the `cldr-data` package instead.

**Comment by mwistrand** [comment]
>Unfortunately, there may not be a way to accomplish this without removing Globalize.js from the i18n method.

I believe I have found a way to manually compile locale-specific messages for the build, and am working on a webpack plugin to do so.

**Comment by sebilasse** [comment]
Can the `cldr-data` become a 'plugin' ?

User story:
_Writing IndieAuth for node_

If the user visits the static (info) pages it is totally fine to download the data in the background.
If the user visits the /auth site, i18n is needed for one purpose : To get one of 40 possible status message. While i18n is needed at page load (it adds 5-6s here ?!) the i18n module does not need the cldr data at all for this particular route ...

**Comment by mwistrand** [comment]
@sebilasse That is essentially what is going to happen. `@dojo/i18n` requires CLDR data for many operations, but it does not require `cldr-data` per se.

By removing `cldr-data` as a dependency, applications will need to pass their own CLDR data to the `@dojo/i18n` ecosystem, which means that those applications that only unformatted messages will not need to load CLDR data all.

**Comment by mwistrand** [comment]
With #54, the beta-blocking portion of this issue has been resolved. At future date we can revisit a means of falling back to `Intl` where available.
