### ISSUE TITLE
cldrjs missing in package.json

### ISSUE THREAD

**Issue by sebilasse** [dojo/i18n#49]
The code says 

> // required for Globalize/Cldr to properly resolve locales in the browser.
> require("cldrjs/dist/cldr/unresolved");

But `cldrjs` is missing in `package.json`

**Comment by dylans** [comment]
@sebilasse

See https://github.com/dojo/i18n/blob/master/package.json#L44-L45

which points to Globalize as a dependency, which then has:

https://github.com/globalizejs/globalize/blob/master/package.json#L73

So it's pulling in cldrjs as a result of pulling in globalize...

How are you using dojo/i18n (via widget-core, or directly)? Are you installing it via npm, e.g. npm install @dojo/i18n?

**Comment by sebilasse** [comment]
@dylans Just installed alpha.4 via npm

**Comment by agubler** [comment]
@sebilasse which version of npm are you using?

**Comment by sebilasse** [comment]
@agubler `2.14.7`

**Comment by agubler** [comment]
@sebilasse we only support npm 3+, we need to add that to the engines in the `package.json`.

**Comment by sebilasse** [comment]
@agubler @dylans : I see. Updating npm and putting the changelog to my endless reading list ;) ... Feel free to close it. Thanks for realtime replies.

**Comment by agubler** [comment]
You're very welcome, the reason we need npm 3+ is that we need all of the dependencies to be pulled to the top level (flatten) `node_modules` which is not supported by npm < 3

**Comment by agubler** [comment]
Closing as per @sebilasse
