### ISSUE TITLE
Issue with .toUrl() on cldr/load

### ISSUE THREAD

**Issue by kitsonk** [dojo/i18n#83]
**Bug**

I am not sure we have the right resolution under AMD with `cldr/load`.  In `todo-mvc-kitchensink` when loading the package via CDN, it attempts to [load some JSON from `./nls/cldr/likelySubtags.json`](https://github.com/dojo/examples/blob/1c963b99db407f671db3746bef1103faee6d16dc/todo-mvc-kitchensink/src/setLocaleData.ts#L8)

This results in the [`require.toURL()` being called](https://github.com/dojo/i18n/blob/f0b1786a582127066abe2276fcd14fb9fa10c5a7/src/cldr/load.ts#L39).  This gets called with the string of `'./nls/cldr/likelySubtags.json'` and the reference module of `@dojo/i18n/cldr/load`, so the URL being returned is relative to the module, instead of the calling module.  It therefore returns the following: `https://unpkg.com/@dojo/i18n@beta1/cldr/nls/cldr/likelySubtags.json`.  The JSON isn't located there...

**Comment by mwistrand** [comment]
Thanks for pointing this out. Everything works correctly with an absolute mid, but, as you discovered, allowing relative paths would require additional logic. Perhaps a contextual `require` could be optionally passed as the first argument, although that would almost certainly require changes to `@dojo/cli-build-webpack` as well. Another alternative is to expect the application itself to pass in the correct mids/URLs if it needs to work with both webpack and an AMD loader.

**Comment by kitsonk** [comment]
I would think that ensuring the caller supplies a FQDN or absolute MID is best, since the relativeness may not always be determinable by `require` by the caller either.

**Comment by kitsonk** [comment]
@matt-gadd pointed out that this might be problematic with Webpack or Node.  Passing contextual require is likely the only way to solve this problem.
