### ISSUE TITLE
Allow hierarchical objects to be used for format replacements

### ISSUE THREAD

**Issue by tomdye** [dojo/i18n#87]
**Enhancement** 

Current implementation of `format` does not allow multi-level objects to be used for string replacement. We should look into implementing this feature.

**Example**

``` typescript
const replacements {
	pet: {
		name: 'Fido'
	},
	person: {
		name: 'John Doe'
	}
}

const messages = this.localizeBundle(nlsBundle);
// messages.announce = '{person.name} has a pet called {pet.name}';

console.log(messages.format('announce', replacements))
// > John Doe has a pet called Fido
```

**Comment by mwistrand** [comment]
Since there is no easy way to allow dot notation within ICU-formatted messages, and since it is preferable to keep behavior consistent within the same functions, I am closing this issue. If dot notation within messages continues to be a need, then we can revisit this at a future date.
